language: node_js

node_js:
  - '4.2.6'

compiler:
  - gcc  

dist: trusty

sudo: required

before_script:
  - chmod +x ./build.*

script:
  - sudo apt-get install -qq cmake
  - npm install -g node-gyp
  - ./build.linux64.sh
  
notifications:
  email:
    on_failure: change
